// Local portfolio image registry.
// Keep these keys stable: portfolio-data.ts and the site components reference them.
// Replace the corresponding files in /public/images/ with your high-resolution WebP images.

export const img = {
  "p01-vishnu-ahir-portrait": "/images/profile/vishnu.webp",
  "p02-bungalow-for-mr-pintubhai-render-view": "/images/projects/pintubhai/p02-bungalow-for-mr-pintubhai-render-view.webp",
  "p03-render-1": "/images/projects/pintubhai/p03-render-1.webp",
  "p04-render-2": "/images/projects/pintubhai/p04-render-2.webp",
  "p05-render-3": "/images/projects/pintubhai/p05-render-3.webp",
  "p06-render-4": "/images/projects/pintubhai/p06-render-4.webp",
  "p07-ground-floor-plan-and-wall-cladding-detail": "/images/projects/pintubhai/p07-ground-floor-plan-and-wall-cladding-detail.webp",
  "p08-front-elevation-and-section": "/images/projects/pintubhai/p08-front-elevation-and-section.webp",
  "p09-tri-pod-residence-exterior-render": "/images/hero/home-hero.webp",
  "p10-tri-pod-residence-street-elevation": "/images/projects/tripod/p10-tri-pod-residence-street-elevation.webp",
  "p11-facade-strategy-diagram": "/images/projects/tripod/p11-facade-strategy-diagram.webp",
  "p12-north-elevation": "/images/projects/tripod/p12-north-elevation.webp",
  "p13-balcony-edge-profile-detail": "/images/projects/tripod/p13-balcony-edge-profile-detail.webp",
  "p14-harekrushna-villa-front-render": "/images/projects/harekrushna/p14-harekrushna-villa-front-render.webp",
  "p15-completed-villa-at-dusk": "/images/projects/harekrushna/p15-completed-villa-at-dusk.webp",
  "p16-site-under-construction": "/images/projects/harekrushna/p16-site-under-construction.webp",
  "p17-foundation-stage": "/images/projects/harekrushna/p17-foundation-stage.webp",
  "p18-structure-completed": "/images/projects/harekrushna/p18-structure-completed.webp",
  "p19-finishing-stage": "/images/projects/harekrushna/p19-finishing-stage.webp",
  "p20-floor-plan": "/images/projects/harekrushna/p20-floor-plan.webp",
  "p21-dining-area": "/images/projects/harekrushna/p21-dining-area.webp",
  "p22-guest-bedroom": "/images/projects/harekrushna/p22-guest-bedroom.webp",
  "p23-master-bedroom": "/images/projects/harekrushna/p23-master-bedroom.webp",
  "p24-puja-room": "/images/projects/harekrushna/p24-puja-room.webp",
  "p25-living-room-interior-render": "/images/projects/harekrushna/p25-living-room-interior-render.webp",
  "p26-living-room-wide-view": "/images/projects/harekrushna/p26-living-room-wide-view.webp",
  "p27-living-room-alternate-angle": "/images/projects/harekrushna/p27-living-room-alternate-angle.webp",
  "p28-tv-unit-detail": "/images/projects/harekrushna/p28-tv-unit-detail.webp",
  "p29-wall-art-detail": "/images/projects/harekrushna/p29-wall-art-detail.webp",
  "p30-study-nook": "/images/projects/harekrushna/p30-study-nook.webp",
  "p31-bedroom-with-study-desk": "/images/projects/harekrushna/p31-bedroom-with-study-desk.webp",
  "p32-master-bedroom": "/images/projects/harekrushna/p32-master-bedroom.webp",
  "p33-bedroom-tv-feature-wall": "/images/projects/harekrushna/p33-bedroom-tv-feature-wall.webp",
  "p34-bharatbhai-bunglow-exterior-render": "/images/projects/bharatbhai/p34-bharatbhai-bunglow-exterior-render.webp",
  "p35-front-exterior-render": "/images/projects/bharatbhai/p35-front-exterior-render.webp",
  "p36-dusk-exterior-render": "/images/projects/bharatbhai/p36-dusk-exterior-render.webp",
  "p37-side-angle-render": "/images/projects/bharatbhai/p37-side-angle-render.webp",
  "p38-outdoor-seating-area": "/images/projects/bharatbhai/p38-outdoor-seating-area.webp",
  "p39-stone-water-feature": "/images/projects/bharatbhai/p39-stone-water-feature.webp",
  "p40-wood-centric-living-area-render": "/images/projects/bharatbhai/p40-wood-centric-living-area-render.webp",
  "p41-glazed-corner-opening-to-garden": "/images/projects/bharatbhai/p41-glazed-corner-opening-to-garden.webp",
  "p42-seating-area-with-wooden-furniture": "/images/projects/bharatbhai/p42-seating-area-with-wooden-furniture.webp",
  "p43-seating-area-alternate-view": "/images/projects/bharatbhai/p43-seating-area-alternate-view.webp",
  "p44-seating-area-with-study-nook": "/images/projects/bharatbhai/p44-seating-area-with-study-nook.webp",
  "r01-living-room-wide-presentation-render": "/images/interiors/r01-living-room-wide-presentation-render.webp",
  "r02-living-room-seating-detail": "/images/interiors/r02-living-room-seating-detail.webp",
  "r03-living-room-sofa-and-art-detail": "/images/interiors/r03-living-room-sofa-and-art-detail.webp",
  "r04-living-room-styling-detail-with-pouf": "/images/interiors/r04-living-room-styling-detail-with-pouf.webp",
  "r05-dining-room-marble-wall-variant": "/images/interiors/r05-dining-room-marble-wall-variant.webp",
  "r06-dining-room-ink-mural-variant": "/images/interiors/r06-dining-room-ink-mural-variant.webp",
  "r07-dining-room-angled-view": "/images/interiors/r07-dining-room-angled-view.webp",
  "r08-dining-room-angled-view-ink-mural": "/images/interiors/r08-dining-room-angled-view-ink-mural.webp",
  "r09-bathroom-wide-render": "/images/interiors/r09-bathroom-wide-render.webp",
  "r10-bathroom-vanity-detail": "/images/interiors/r10-bathroom-vanity-detail.webp",
  "r11-bathroom-shower-detail": "/images/interiors/r11-bathroom-shower-detail.webp",
} as const;
